travis:
  secure:
    BINSTAR_TOKEN: Xe0ZG5wKVdSJ8f6SBrWwkS+BnzAr0Nwtm7Wdfrtvw94G9V6fRMb8PRzt+lhuNMqLqXbzGT3jOTNVMQOeP6FrjlnhpaL9O9BQF8xRLTiu7TN7xCQHy4/Mh1B9uVAnAUC5S1AeWGxPtUGpM+E0NP4A/yZzbUL+AHcsfNfglgM6H+9deD5ZhScsyqGOhsbqhHijFvnekLMaE5kto6pZp7he8vvn2w+gkQl8yr572Fn5k6+aFinpV7qY8aKOtRHILl88n9ayqBvI0zO+7+/UY3+rS/QrBIZINRcE8xcFBdwHtAJtAhm2YxQMgHQCyJZWiAWzykTXX58KKAedlyJIPdol9RXfwh2xCge5S+1gfjCdihfacJYyRZbcEB08eJzG7po3iXOcI/0g+rUrHW6RdMnuL/K4LwdXgnNPKzeHbwl2SUdqEc0Xr+YFbeI7WJlbcAGO7S7AjFsok5TDWCw2qO4Zba/vz0ZNt4cibXiJ3k1C13jrM46+Wab3Bx832Si6UZqrzy2Hz7+p2kES61MV+KNOLJEl0M9tbH+DUxAH5tk+mG9ZIkjETKCQ1gb3HcrkcAYCw1gWN+2clz3BpVcluu6uTI24f/M0f8mE28UB3pMR3NX0kTRFISAWrL8GCGyqADs2TMjo7C5RIn/wYILm75iMhtNyFif0OU7vdaK/rRlB/N0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
